### ISSUE TITLE
hexagon logo

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [stevecondylios/iteratoR#1]
Hello

I came up with a design that use your idea of a circle , 2 styles. Things can be modified. Hope you like. 
- Zane Dax

![Screen Shot 2022-08-28 at 10 19 50 AM](https://user-images.githubusercontent.com/55933131/187084115-f2e51308-e6e4-4790-a1a8-0f011408f5e3.png)

**Comment by stevecondylios** [comment]
incredible! Both look fantastic.

**Comment by PythonCoderUnicorn** [comment]
style 1

![hexagon-iteratoR](https://user-images.githubusercontent.com/55933131/187101942-2441d954-1d1d-4721-aafc-5be8ecca1094.png)

**Comment by PythonCoderUnicorn** [comment]
style 2

![hexagon-iterator-1](https://user-images.githubusercontent.com/55933131/187101984-be0cf5f2-a031-463f-87c8-bcef4690cf6b.png)

**Comment by stevecondylios** [comment]
We're live: https://github.com/stevecondylios/iteratoR#iterator-

Looks awesome, thanks again Zane!
